# Generated by Django 5.1.6 on 2025-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posto', models.CharField(default='Não informado', max_length=100)),
                ('telefone', models.CharField(default='62999999999', max_length=15)),
                ('ipv4', models.GenericIPAddressField(default='0.0.0.0')),
                ('solicitante', models.CharField(default='Solicitante', max_length=100)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em atendimento', 'Em atendimento'), ('Fechado', 'Fechado')], default='Aberto', max_length=15)),
                ('responsavel', models.CharField(max_length=255, null=True)),
                ('resposta', models.CharField(max_length=500, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_posto', models.CharField(default='unidade ou posto', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(default='Lider', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
