# Generated by Django 5.1.6 on 2025-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posto', models.CharField(default='Não informado', max_length=100)),
                ('telefone', models.CharField(default='62999999999', max_length=15)),
                ('ipv4', models.GenericIPAddressField(default='0.0.0.0')),
                ('solicitante', models.CharField(default='Solicitante', max_length=100)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em atendimento', 'Em atendimento'), ('Fechado', 'Fechado')], default='Aberto', max_length=15)),
                ('acao', models.CharField(max_length=255, null=True)),
                ('resposta', models.CharField(max_length=500, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_posto', models.CharField(default='unidade ou posto', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(default='Atendente', max_length=20)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
