# Generated by Django 5.1.6 on 2025-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_posto', models.CharField(default='unidade ou posto', max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email_unidade', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo', models.CharField(default='Cliente', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='acao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='ipv4',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='posto',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='chamado',
            name='resposta',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.CharField(default='Solicitante', max_length=100),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em atendimento', 'Em atendimento'), ('Fechado', 'Fechado')], default='Aberto', max_length=15),
        ),
        migrations.AddField(
            model_name='chamado',
            name='telefone',
            field=models.CharField(default='62999999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
